---
- hosts: all
  vars_prompt:
    - name: repo_url
      prompt: "Enter repository URL"
      private: no
  tasks:
    - name: Pull latest from raspberry-pi-ansible-bootstrap repo
      git:
        repo: '{{ repo_url }}'
        dest: /home/ansible_user/code/app
      become: true
    - name: Start application
      command: "pm2 start /home/ansible_user/code/raspberry-pi-ansible-bootstrap/app.js"
      become: true
      register: ret
      failed_when: >-
        ret.rc != 0 and
        '[PM2][ERROR] Script already launched' not in ret.stderr
      changed_when: >-
        ret.rc != 0 and
        '[PM2][ERROR] Script already launched' not in ret.stderr
