---
- hosts: all
  vars:
    NODEJS_VERSION: "16"
    ansible_distribution_release: "buster"
    application_repo_url: "{{ lookup('file', '/home/ansible_user/code/raspberry-pi-ansible-bootstrap/app-repo-url.txt') }}"
  tasks:
  - name: Setup cron job to run ansible
    become: yes
    become_method: sudo
    cron:
      name: "ansible update"
      user: "ansible_user"
      hour: "*"
      minute: "*/5"
      job: "ansible-playbook /home/ansible_user/code/raspberry-pi-ansible-bootstrap/provision.yml -i /home/ansible_user/inventory.ini"
      state: present
  - name: Pull latest from raspberry-pi-ansible-bootstrap repo
    git:
      repo: https://github.com/aautar/raspberry-pi-ansible-bootstrap.git
      dest: /home/ansible_user/code/raspberry-pi-ansible-bootstrap
  - name: Install gpg
    apt:
      name: ['gpg']
      state: present
    become: true
    tags: packages
  - name: Install the gpg key for nodejs LTS
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present
    become: true
  - name: Install the nodejs LTS repos
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
      state: present
      update_cache: yes
    become: true
  - name: Install nodejs
    apt:
      name: nodejs
      state: present
    become: true
  - name: Install PM2
    npm:
      name: pm2
      global: yes
      state: present
    become: true
  - name: Execute post-provision plays
    import_tasks: /home/ansible_user/code/raspberry-pi-ansible-bootstrap/tasks/app-tasks.yml
    vars:
      app_repo_url: "{{application_repo_url}}"
