---
  - name: Pull latest from application repo
    git:
      repo: '{{ app_repo_url }}'
      dest: /home/ansible_user/code/app
    become: true
  - name: Start application
    command: "pm2 start /home/ansible_user/code/app/app.js"
    become: true
    register: ret
    failed_when: >-
      ret.rc != 0 and
      '[PM2][ERROR] Script already launched' not in ret.stderr
    changed_when: >-
      ret.rc != 0 and
      '[PM2][ERROR] Script already launched' not in ret.stderr
