---
  - debug:
      msg: "app_repo_url = {{ app_repo_url }}"
  - debug:
      msg: "app_folder = {{ app_folder }}"
  - name: Pull latest from application repo
    git:
      repo: "{{ app_repo_url }}"
      dest: /home/ansible_user/code/app
      clone: yes
      update: yes
      force: yes
      accept_hostkey: yes
  - name: Install application dependencies
    shell: npm install
    args:
      chdir:  "/home/ansible_user/code/app/{{app_folder}}"
  - set_fact:
      newAppVersion: "{{ (lookup('file', '/home/ansible_user/code/app/' + app_folder + '/package.json') | from_json).get('version') }}"
  - debug:
      msg: "Version of app pulled down = {{ newAppVersion }}"
  - name: Get info on running app
    command: "pm2 jlist"
    register: pm2_proc_list
  - debug:
      msg: "pm2_proc_list = {{ (pm2_proc_list.stdout | from_json) }}"
  - set_fact:
      existingAppVersion: "{{ item.pm2_env.version }}"
    when: item.name == "app"
    with_items: "{{ pm2_proc_list.stdout | from_json }}"
  - debug:
      msg: "Version of app running = {{ existingAppVersion }}"
  - name: Start application
    command: "pm2 start /home/ansible_user/code/app/{{app_folder}}/src/app.js --watch"
    register: ret
    failed_when: >-
      ret.rc != 0 and
      '[PM2][ERROR] Script already launched' not in ret.stderr
    changed_when: >-
      ret.rc != 0 and
      '[PM2][ERROR] Script already launched' not in ret.stderr
