---
  - debug:
      msg: "app_repo_url = {{ app_repo_url }}"
  - debug:
      msg: "app_folder = {{ app_folder }}"
  - name: Pull latest from application repo
    git:
      repo: "{{ app_repo_url }}"
      dest: /home/ansible_user/code/app
      clone: yes
      update: yes
      force: yes
      accept_hostkey: yes
  - name: Install application dependencies
    shell: npm install
    args:
      chdir:  "/home/ansible_user/code/app/{{app_folder}}"
  - name: Start application
    command: "pm2 start /home/ansible_user/code/app/{{app_folder}}/src/app.js --watch"
    register: ret
    failed_when: >-
      ret.rc != 0 and
      '[PM2][ERROR] Script already launched' not in ret.stderr
    changed_when: >-
      ret.rc != 0 and
      '[PM2][ERROR] Script already launched' not in ret.stderr
