---
- name: Setup logrotate for ansible.log
  become: true
  blockinfile:
    path: "/etc/logrotate.d/{{ item.path }}"
    block: "{{ item.conf }}"
    create: true
  loop: "{{ lp_logrotate_confd }}"
  vars:
    lp_logrotate_confd:
      - path: ansible
        conf: |
          /var/log/ansible.log {
             daily
             rotate 3
             size 10M
             compress
             delaycompress
          }
- name: Update logrotate for rsyslog
  become: true
  blockinfile:
    path: "/etc/logrotate.d/{{ item.path }}"
    block: "{{ item.conf }}"
    create: true
  loop: "{{ lp_logrotate_confd }}"
  vars:
    lp_logrotate_confd:
      - path: rsyslog
        conf: |
          /var/log/syslog
          /var/log/mail.info
          /var/log/mail.warn
          /var/log/mail.err
          /var/log/mail.log
          /var/log/daemon.log
          /var/log/kern.log
          /var/log/auth.log
          /var/log/user.log
          /var/log/lpr.log
          /var/log/cron.log
          /var/log/debug
          /var/log/messages
          {
            rotate 4
            daily
            size 10M
            missingok
            notifempty
            compress
            delaycompress
            sharedscripts
            postrotate
            /usr/lib/rsyslog/rsyslog-rotate
            endscript
          }
