---
- name: Check internet connection
  command: "ping -c4 github.com"
  register: internet_ret
  changed_when: internet_ret.rc != 0
  ignore_errors: yes
- name: Restart machine if network down
  reboot:
    reboot_timeout: 300
  become: true
  when: internet_ret.rc != 0
