---
- name: Check internet connection
  command: "ping -c4 github.com"
  register: internet_ret
  changed_when: internet_ret.rc != 0
  ignore_errors: yes
- name: Restart network
  command: "/etc/init.d/networking restart"
  become: true
  when: internet_ret.rc != 0
