---
- name: Check internet connection
  command: "ping -c4 github.com"
  register: internet_ret
- name: Restart network
  command: "/etc/init.d/networking restart"
  become: true
  when: internet_ret != 0
